language: node_js

node_js:
  - "6"

addons:
  sauce_connect: true

before_script:
  - npm install

script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: "69c89889-126a-4602-85c0-bf949e162f78"

notifications:
  email:
    - beats.1213@gmail.com
