language: node_js

node_js:
  - "6"

addons:
  sauce_connect: true

before_script:
  - npm install

script:
  - npm test

after_success:
  - npm deploy

notifications:
  email:
    - beats.1213@gmail.com
