language: node_js

node_js:
  - "6"

addons:
  sauce_connect: true

before_script:
  - npm install

script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: "1ed03909-4b32-4d4a-bcf3-6e45d3d7143c"

after_deploy:
  - npm run sauce

notifications:
  email:
    - beats.1213@gmail.com
